//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepperWebApI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetail
    {
        public int Id { get; set; }
        public string AccountNo { get; set; }
        public string IFSC { get; set; }
        public string PanCardNo { get; set; }
        public string AadharCardNo { get; set; }
        public int DetailId { get; set; }
    
        public virtual Detail Detail { get; set; }
    }
}
