//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepperWebApI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentStatu
    {
        public int Id { get; set; }
        public string Company { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string CTC { get; set; }
        public System.DateTime WorkingFrom { get; set; }
        public int DetailId { get; set; }
    
        public virtual Detail Detail { get; set; }
    }
}
